services:
  backend:
    build: ./backend
    environment:
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_USER_PASSWORD}
      - DB_HOST=db
      - DB_PORT=3306
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/code
      - /code/node_modules/
    ports:
      - 3000:3000
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
    ports:
      - ${FORWARD_DB_PORT:-3306}:3306